### ISSUE TITLE
LogHttpGPT: Error: ProcessResponse (161088): Request failed

### ISSUE THREAD

**Issue by zixixr** [lucoiso/UEHttpGPT#12]
It seems that if I talk too many rounds, there will always be a error like this, and after this error, no more conversation could be made

**Comment by lucoiso** [comment]
Hi! @zixixr 

Can you enable the internal logs to check what's happening? Maybe its related to the max tokens and you will need to clear the chat history to try again.


Project Settings -> Plugins -> HttpGPT

**Comment by zixixr** [comment]
So the maximum is 2048 tokens? Appearently it couldn't hold much information when it's Chinese, from OPENAI documents, it should be 4096 right?

**Comment by lucoiso** [comment]
@zixixr 

Already changed this in the development branch (will merge soon), the max now is 32768: https://github.com/lucoiso/UEHttpGPT/tree/development 😁
