### ISSUE TITLE
Set system for chat mode

### ISSUE THREAD

**Issue by zixixr** [lucoiso/UEHttpGPT#13]
Is there a place that we could set the system role? Just like below or the playgournd in chat mode, that you could set various roles and cusotmize the response.

openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Who won the world series in 2020?"},
        {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
        {"role": "user", "content": "Where was it played?"}
    ]
)

**Comment by lucoiso** [comment]
@zixixr Added to the development branch! : )
