### ISSUE TITLE
Check and add support for UE4.27 & UE5.0

### ISSUE THREAD

**Issue by lucoiso** [lucoiso/UEHttpGPT#17]

**Comment by NCMcClure** [comment]
Hey there! Absolutely love what you're doing here and how well made this plugin is for 5.1! Kudos! Just wanted to add my +1 for having 4.27 support!

Also do you have somewhere to donate for your awesome work? Thanks!

**Comment by lucoiso** [comment]
> Hey there! Absolutely love what you're doing here and how well made this plugin is for 5.1! Kudos! Just wanted to add my +1 for having 4.27 support, would be awesome for me to test out some new features in my project. Hopefully it's not too difficult to implement, would love to start testing it out soon!
> 
> Also do you have somewhere to donate for your awesome work? Thanks!
> 
> Edit: Nevermind, just realized you accept sponsors!

Thanks! :)

I'll check this soon 🥳

**Comment by lucoiso** [comment]
## Progress Screenshot

![image](https://user-images.githubusercontent.com/77353979/226904304-f5267445-ed89-40e9-8395-2205f47b0714.png)
