### ISSUE TITLE
I cant see the plugin to use the API in the "advanced settings" menu

### ISSUE THREAD

**Issue by brunsonator3** [lucoiso/UEHttpGPT#33]
I'm not sure what's wrong. I can access it in tools, but it does not work. And when I go to editor preferences I cant find the httpchatgpt plug in

**Comment by lucoiso** [comment]
Hello @brunsonator3 ! :)

You can find the settings in **Project Settings** -> Plugins -> HttpGPT

![image](https://user-images.githubusercontent.com/77353979/228601117-003de0da-5a4f-48ba-be8d-53afae0dd898.png)

![image](https://user-images.githubusercontent.com/77353979/228601249-23345e53-8246-4ea0-b9cd-c89d16c83d71.png)

**Comment by brunsonator3** [comment]
> Hello @brunsonator3 ! :)
> 
> You can find the settings in **Project Settings** -> Plugins -> HttpGPT
> 
> ![image](https://user-images.githubusercontent.com/77353979/228601117-003de0da-5a4f-48ba-be8d-53afae0dd898.png)
> 
> ![image](https://user-images.githubusercontent.com/77353979/228601249-23345e53-8246-4ea0-b9cd-c89d16c83d71.png)

Thanks it worked!!!
