### ISSUE TITLE
Get GPT response sentence by sentence

### ISSUE THREAD

**Issue by zixixr** [lucoiso/UEHttpGPT#42]
Hi @lucoiso , I noticed that GPT api actually replies word by word. And to generate the msg string, it would take a while for GPT to reply all the words. For example, a 200 words paragaph, it might take GPT 10 seconds to reply the whole paragraph. 

So is it possible to get the response sentence by sentence, for example I could set a range, generate a message string when the accumulated response has been larger than 10 words, and when they system comes across symbols such as  [, . ! ?] ?

The reason to do that is to reduce the wait time. As long as I got a senetence, I'll feed the message to Azure to get audio and blendshapes, instead of waiting for the whole thing to be generated.

**Comment by Alex-Rynkowski** [comment]
Out of curiousity, could you not use Regex for that? That's how we are doing it in our project

**Comment by kqkq** [comment]
There's a dedicated plugin:

String Splitter for ChatGPT

https://www.unrealengine.com/marketplace/en-US/product/string-splitter-for-chatgpt
