### ISSUE TITLE
No response depending of window context

### ISSUE THREAD

**Issue by wyhwz** [lucoiso/UEHttpGPT#43]
The access problem of a single window is suspected to be restricted. After asking a few questions, there is no response. It can be used normally after restarting, but it is not related to the problem of the previous window.

**Comment by lucoiso** [comment]
Hello @wyhwz ! 
Sorry for the delay! :S 

Any output being printed in the logs or you're just not receiving any responses? And this issue is occurring with the HttpGPT Chat or using functions in a project?
