### ISSUE TITLE
Feature: Stable Diffusion

### ISSUE THREAD

**Issue by Tobe2d** [lucoiso/UEHttpGPT#50]
Feature Request.

Is it posible to dd Stable Diffusion through using API key?
It will be great if we can use it with Automatic1111 API

**Comment by lucoiso** [comment]
Hi! :)
Thanks for your suggestion!

Integration of the Stable Diffusion and other systems would be great! Maybe I'll try adding this in the future! :)

**Comment by Tobe2d** [comment]
Cool, let me know if you want me to test anything :-)

**Comment by lucoiso** [comment]
Currently focusing only on OpenAI' APIs. Maybe will reopen this task in the future.
