### ISSUE TITLE
Internal Logs Enabled but still not working

### ISSUE THREAD

**Issue by Rotz360** [lucoiso/UEHttpGPT#60]
Hi Everyone, 

I'm having an issue with the ChatGPT Plugin in UNreal Engine 5.1.1.
I enabled the plugin and turned on the Internal Logs as the assistant said but it still not working and keep saying to me to enable the internal logs.
Any suggestions?

**Comment by lucoiso** [comment]
Hello! Which version of the plugin are you using? And can you ensure that all settings are correct in Project settings -> Plugins -> HttpGPT?

If you are using the task with custom options can you ensure that the structures contains valid parameters?

And can you send me the logs with Internal Logs enabled to check whats happening? :)

My email: contatolukevboas@gmail.com

**Comment by Rotz360** [comment]
Hi @lucoiso, 

I just sent you an Email with all the informations you requested!

Thank You!

**Comment by KaptainKratos** [comment]
Did we get this resolved? I am having the same issue.

**Comment by Rotz360** [comment]
@KaptainKratos unfortunately not yet...

**Comment by lucoiso** [comment]
Hello! Sorry for the delay. Just replied the email! :)

The "check the logs" error is generally related to the settings in Project Settings. As this plugin just connects to OpenAI APIs, you'll need the API key to send requests:

https://github.com/lucoiso/UEHttpGPT/wiki/1.-Setup#getting-the-openai-api-key
