### ISSUE TITLE
Crash "OnProgressUpdated" when switching map

### ISSUE THREAD

**Issue by Alex-Rynkowski** [lucoiso/UEHttpGPT#67]
I sometimes experience a crash when I switch map in the Editor:

![image](https://github.com/lucoiso/UEHttpGPT/assets/66161323/1f961ff9-38a7-4ca5-84fc-fc7493bc3853)

**Comment by lucoiso** [comment]
Adjusted the critical section to use a try lock. Couldn't replicate the crash after the change.
