### ISSUE TITLE
HttpGPT Is crashing lately

### ISSUE THREAD

**Issue by nobeknia** [lucoiso/UEHttpGPT#69]
Hello! there is something weird that is happening lately with this plugin in my project. Before was running perfect with any crashes, but lately started to crash (overall on packaged builds) and I don't understand why. Any idea what could be? Here is a link with the crash screenshot: https://pbs.twimg.com/media/F0qEnmnXoAAtJqW?format=jpg&name=large

**Comment by lucoiso** [comment]
Added verifications to the request and response before forwarding them. Couldn't replicate the crash after the change.
