### ISSUE TITLE
HttpGPT.uplugin (1.5.4, HttpGPT_UE51.zip file) uses 4.27 "WhitelistPlatforms" instead of 5.x "PlatformAllowList"

### ISSUE THREAD

**Issue by GreebleGraphics** [lucoiso/UEHttpGPT#75]
Greetings,

HttpGPT.uplugin (1.5.4, HttpGPT_UE51.zip file) uses the 4.27 term "WhitelistPlatforms" instead of the 5.x term "[PlatformAllowList](https://dev.epicgames.com/community/snippets/7YD/ue4-to-ue5-plugin-upgrade-notes)."

This shouldn't cause a problem for most users, since Unreal 5.x will ignore "WhitelistPlatforms" in the UPLUGIN file. However, I thought I should report it.

Thank you again for writing HttpGPT,

Jen

![image](https://github.com/lucoiso/UEHttpGPT/assets/95188950/1355a545-a690-4409-944e-ef5b2a48a531)

**Comment by lucoiso** [comment]
Thankss! Will be updated in the next submission! 😆
